name: Ubuntu

on:
  push:
    branches:
      - "master"
      - "3d_graphic_method"
  pull_request:
    branches:
      - "master"
      - "3d_graphic_method"

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: apt update
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@v1.2.2
        with:
          packages: build-essential libglu1-mesa-dev freeglut3-dev mesa-common-dev libglfw3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
          version: 1.0
          execute_install_scripts: true

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}