name: Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install build-essential -y
          sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
          sudo apt-get install libglfw3-dev
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
          git clone https://github.com/Dav1dde/glad.git
          cd glad
          cmake ./
          make
          sudo cp -a include /usr/local/
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

      - name: Build with CMake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{github.workspace}}/build
          cc: ${{ matrix.config.cc }}
          cxx: ${{ matrix.config.cxx }}
          configure-options: -G Ninja
          build-type: ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build/tests
        run: ctest -C ${{env.BUILD_TYPE}} -V